export type ItemType =
  | "assignment"
  | "quiz"
  | "exam"
  | "project"
  | "lecture"
  | "homework";
export type ItemStatus = "not-started" | "in-progress" | "completed";

export interface AcademicItem {
  id: string;
  title: string;
  class: string;
  classCode: string;
  type: ItemType;
  status: ItemStatus;
  dueDate: string;
  time?: string;
  description?: string;
  location?: string;
  grade?: number; // Score out of 100
  isLate?: boolean; // Late submission toggle
  daysLate?: number; // Number of days late
  isFinal?: boolean; // Is this a final exam?
  gradeCategory?: "exam" | "final" | "hw" | "quiz" | "project" | "lab" | "participation"; // Grade weight category
  semesterId?: string; // Which semester this item belongs to
}

export interface ClassInfo {
  code: string;
  name: string;
  color: string;
  hasLatePenalty: boolean;
  killSwitch?: string;
}

export interface Semester {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  classes: ClassInfo[];
  gradeWeights: Record<string, Record<string, { weight: number; label: string }>>;
}

export const defaultClasses: ClassInfo[] = [
  {
    code: "ECON330",
    name: "Comparative Economic Systems",
    color: "bg-chart-1",
    hasLatePenalty: true,
  },
  {
    code: "MATH120",
    name: "Calculus for Business Analysis",
    color: "bg-chart-2",
    hasLatePenalty: true,
    killSwitch: "Missing the final results in a failing grade",
  },
  {
    code: "MIS180",
    name: "Principles of Information Systems",
    color: "bg-chart-3",
    hasLatePenalty: false,
    killSwitch: "Missing the final results in a failing grade",
  },
  {
    code: "ECON321",
    name: "Intermediate Microeconomic Theory",
    color: "bg-chart-4",
    hasLatePenalty: false,
  },
];

// Initial semester with current classes
const initialClasses = defaultClasses; // Declare the classes variable
export const initialSemesters: Semester[] = [
  {
    id: "spring-2026",
    name: "Spring 2026",
    startDate: "2026-01-12",
    endDate: "2026-05-15",
    classes: defaultClasses,
    gradeWeights: {
      MATH120: {
        exam: { weight: 0.55, label: "3 Exams" },
        final: { weight: 0.15, label: "Final Exam" },
        hw: { weight: 0.15, label: "Homework" },
        quiz: { weight: 0.15, label: "Quizzes" },
      },
      MIS180: {
        exam: { weight: 0.3, label: "Exams" },
        final: { weight: 0.2, label: "Final Exam" },
        lab: { weight: 0.3, label: "Lab Projects" },
        quiz: { weight: 0.1, label: "Quizzes" },
        participation: { weight: 0.1, label: "Participation" },
      },
      ECON330: {
        exam: { weight: 0.5, label: "Exams" },
        final: { weight: 0.25, label: "Final Exam" },
        project: { weight: 0.2, label: "Projects" },
        quiz: { weight: 0.05, label: "Quizzes" },
      },
      ECON321: {
        exam: { weight: 0.4, label: "Exams" },
        final: { weight: 0.3, label: "Final Exam" },
        quiz: { weight: 0.3, label: "Quizzes" },
      },
    },
  },
];

// Grade weights per class
export const defaultGradeWeights: Record<
  string,
  Record<string, { weight: number; label: string }>
> = {
  MATH120: {
    exam: { weight: 0.55, label: "3 Exams" },
    final: { weight: 0.15, label: "Final Exam" },
    hw: { weight: 0.15, label: "Homework" },
    quiz: { weight: 0.15, label: "Quizzes" },
  },
  MIS180: {
    exam: { weight: 0.3, label: "Exams" },
    final: { weight: 0.2, label: "Final Exam" },
    lab: { weight: 0.3, label: "Lab Projects" },
    quiz: { weight: 0.1, label: "Quizzes" },
    participation: { weight: 0.1, label: "Participation" },
  },
  ECON330: {
    exam: { weight: 0.5, label: "Exams" },
    final: { weight: 0.25, label: "Final Exam" },
    project: { weight: 0.2, label: "Projects" },
    quiz: { weight: 0.05, label: "Quizzes" },
  },
  ECON321: {
    exam: { weight: 0.4, label: "Exams" },
    final: { weight: 0.3, label: "Final Exam" },
    quiz: { weight: 0.3, label: "Quizzes" },
  },
};

export const initialItems: AcademicItem[] = [
  // ==========================================
  // MIS 180 - Principles of Information Systems
  // ==========================================
  {
    id: "mis180-quiz-ai",
    title: "AI Quizzes & Simulation Activity",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-02-01",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "mis180-lec1",
    title: "Strategy and Information Systems",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-02",
    time: "Async",
  },
  {
    id: "mis180-lec2",
    title: "Business Intelligence, Analytics, and AI",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-09",
    time: "Async",
  },
  {
    id: "mis180-exam1",
    title: "LECTURE EXAM 1 (Chapters 1-3)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "exam",
    status: "not-started",
    dueDate: "2026-02-16",
    time: "In Lab",
    description: "Feb 16-20 window",
    gradeCategory: "exam",
  },
  {
    id: "mis180-lec3",
    title: "Hardware, Software, & Mobile Systems",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-23",
    time: "Async",
  },
  {
    id: "mis180-lec4",
    title: "Database Processing (Module 5)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-02",
    time: "Async",
  },
  {
    id: "mis180-lec5",
    title: "The Cloud (Module 6)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-09",
    time: "Async",
  },
  {
    id: "mis180-lec6",
    title: "Collaboration Information Systems (Module 7)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-16",
    time: "Async",
  },
  {
    id: "mis180-exam2",
    title: "LECTURE EXAM 2 (Chapters 4-7)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "exam",
    status: "not-started",
    dueDate: "2026-03-23",
    time: "In Lab",
    description: "Mar 23-27 window",
    gradeCategory: "exam",
  },
  {
    id: "mis180-assign1",
    title: "Lab Assignment 1 Due (Excel)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "assignment",
    status: "not-started",
    dueDate: "2026-04-06",
    time: "23:59",
    gradeCategory: "lab",
  },
  {
    id: "mis180-lec7",
    title: "Processes & Information Systems (Mod 8)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-06",
    time: "Async",
  },
  {
    id: "mis180-lec8",
    title: "Social Media Information Systems (Mod 9)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-13",
    time: "Async",
  },
  {
    id: "mis180-lec9",
    title: "Cybersecurity (Module 10)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-20",
    time: "Async",
  },
  {
    id: "mis180-lec10",
    title: "IS Development (Module 11)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-27",
    time: "Async",
  },
  {
    id: "mis180-assign2",
    title: "Lab Assignment 2 Due (Tableau)",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "assignment",
    status: "not-started",
    dueDate: "2026-05-04",
    time: "23:59",
    gradeCategory: "lab",
  },
  {
    id: "mis180-lec11",
    title: "Final Review",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-05-04",
    time: "Async",
  },
  {
    id: "mis180-final",
    title: "CUMULATIVE FINAL EXAM",
    class: "Principles of Information Systems",
    classCode: "MIS180",
    type: "exam",
    status: "not-started",
    dueDate: "2026-05-13",
    time: "08:00",
    isFinal: true,
    gradeCategory: "final",
  },

  // ==========================================
  // ECON 330 - Comparative Economic Systems
  // ==========================================
  {
    id: "econ330-lec1",
    title: "Classifying Economic Systems",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "completed",
    dueDate: "2026-02-02",
    time: "15:30",
  },
  {
    id: "econ330-lec2",
    title: "Classifying Economic Systems",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-04",
    time: "15:30",
  },
  {
    id: "econ330-proj1",
    title: "Project 1 Due",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "project",
    status: "not-started",
    dueDate: "2026-02-04",
    time: "23:59",
    gradeCategory: "project",
  },
  {
    id: "econ330-lec3",
    title: "Economic Systems and Outcomes",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-09",
    time: "15:30",
  },
  {
    id: "econ330-lec4",
    title: "Economic Systems & Outcomes",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-11",
    time: "15:30",
  },
  {
    id: "econ330-quiz1",
    title: "Quiz 1 Due",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-02-11",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "econ330-lec5",
    title: "Evolution of Economic Systems",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-16",
    time: "15:30",
  },
  {
    id: "econ330-lec6",
    title: "Evolution of Economic Systems",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-18",
    time: "15:30",
  },
  {
    id: "econ330-quiz2",
    title: "Quiz 2 Due",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-02-18",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "econ330-exam1",
    title: "EXAM 1 (Chapters 1-4)",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "exam",
    status: "not-started",
    dueDate: "2026-02-25",
    time: "15:30",
    gradeCategory: "exam",
  },
  {
    id: "econ330-lec7",
    title: "Theory of Capitalism (Ch. 6)",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-02",
    time: "15:30",
    description: "Mar 2-4",
  },
  {
    id: "econ330-lec8",
    title: "Theory of Planned Socialism (Ch. 7)",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-09",
    time: "15:30",
    description: "Mar 9-11",
  },
  {
    id: "econ330-proj2",
    title: "Project 2 Due",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "project",
    status: "not-started",
    dueDate: "2026-03-11",
    time: "23:59",
    gradeCategory: "project",
  },
  {
    id: "econ330-lec9",
    title: "Soviet Command Economy (Ch. 14)",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-16",
    time: "15:30",
    description: "Mar 16-18",
  },
  {
    id: "econ330-quiz3",
    title: "Quiz 3 Due",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-03-18",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "econ330-lec10",
    title: "Anglo-Saxon Model & U.S. Economy",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-23",
    time: "15:30",
    description: "Mar 23-25",
  },
  {
    id: "econ330-lec11",
    title: "The European Model (Ch. 12)",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-06",
    time: "15:30",
    description: "Apr 6-8",
  },
  {
    id: "econ330-exam2",
    title: "EXAM 2",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "exam",
    status: "not-started",
    dueDate: "2026-04-08",
    time: "In Class",
    gradeCategory: "exam",
  },
  {
    id: "econ330-quiz4",
    title: "Quiz 4 Due",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-04-08",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "econ330-lec12",
    title: "The Asian Model (Ch. 13)",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-20",
    time: "15:30",
    description: "Apr 20-22",
  },
  {
    id: "econ330-lec13",
    title: "Peoples Republic of China (Ch. 15)",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-27",
    time: "15:30",
    description: "Apr 27-29",
  },
  {
    id: "econ330-proj3",
    title: "Project 3 Due",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "project",
    status: "not-started",
    dueDate: "2026-04-29",
    time: "23:59",
    gradeCategory: "project",
  },
  {
    id: "econ330-quiz5",
    title: "Quiz 5 Due",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-05-06",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "econ330-final",
    title: "COMPREHENSIVE FINAL EXAM",
    class: "Comparative Economic Systems",
    classCode: "ECON330",
    type: "exam",
    status: "not-started",
    dueDate: "2026-05-13",
    time: "13:30",
    isFinal: true,
    gradeCategory: "final",
  },

  // ==========================================
  // ECON 321 - Intermediate Microeconomic Theory
  // ==========================================
  {
    id: "econ321-lec1",
    title: "The Market (Ch. 1)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-03",
    time: "TBD",
  },
  {
    id: "econ321-lec2",
    title: "Budget Constraint (Ch. 2)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-05",
    time: "TBD",
  },
  {
    id: "econ321-lec3",
    title: "Preferences (Ch. 3)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-10",
    time: "TBD",
  },
  {
    id: "econ321-lec4",
    title: "Preferences (Ch. 3)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-12",
    time: "TBD",
  },
  {
    id: "econ321-quiz1",
    title: "QUIZ 1 (Chapters 1-3)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-02-17",
    time: "In Class",
    gradeCategory: "quiz",
  },
  {
    id: "econ321-lec5",
    title: "Utility (Ch. 4)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-19",
    time: "TBD",
  },
  {
    id: "econ321-lec6",
    title: "Choice (Ch. 5)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-24",
    time: "TBD",
  },
  {
    id: "econ321-lec7",
    title: "Choice (Ch. 5)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-02-26",
    time: "TBD",
  },
  {
    id: "econ321-lec8",
    title: "Midterm Review",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-05",
    time: "TBD",
  },
  {
    id: "econ321-midterm",
    title: "MIDTERM EXAM (In Class)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "exam",
    status: "not-started",
    dueDate: "2026-03-10",
    time: "In Class",
    gradeCategory: "exam",
  },
  {
    id: "econ321-lec9",
    title: "Technology (Ch. 19)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-12",
    time: "TBD",
  },
  {
    id: "econ321-lec10",
    title: "Profit Maximization (Ch. 20)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-03-24",
    time: "TBD",
    description: "Mar 24-26",
  },
  {
    id: "econ321-lec11",
    title: "Profit Maximization (Ch. 20)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-07",
    time: "TBD",
    description: "Apr 7-9",
  },
  {
    id: "econ321-quiz2",
    title: "QUIZ 2 (Chapters 19 & 20)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-04-14",
    time: "In Class",
    gradeCategory: "quiz",
  },
  {
    id: "econ321-lec12",
    title: "Firm Supply (Ch. 23)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-16",
    time: "TBD",
    description: "Apr 16-21",
  },
  {
    id: "econ321-lec13",
    title: "Game Theory (Ch. 29)",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-04-23",
    time: "TBD",
    description: "Apr 23-30",
  },
  {
    id: "econ321-lec14",
    title: "Final Review",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "lecture",
    status: "not-started",
    dueDate: "2026-05-05",
    time: "TBD",
  },
  {
    id: "econ321-final",
    title: "FINAL EXAM",
    class: "Intermediate Microeconomic Theory",
    classCode: "ECON321",
    type: "exam",
    status: "not-started",
    dueDate: "2026-05-07",
    time: "08:00",
    isFinal: true,
    gradeCategory: "final",
  },

  // ==========================================
  // MATH 120 - Calculus for Business Analysis
  // ==========================================
  {
    id: "math120-hw1",
    title: "Finish Review Sections R.1-R.4",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-02-07",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-hw2",
    title: "Finish Review Sections R.5-R.7",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-02-14",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-hw3",
    title: "Finish Sections 1.1-1.4",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-02-21",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-exam1",
    title: "EXAM #1",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "exam",
    status: "not-started",
    dueDate: "2026-02-26",
    time: "08:00",
    gradeCategory: "exam",
  },
  {
    id: "math120-quiz1",
    title: "Ch 1 & 2 Skills Quizzes Due",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-02-28",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "math120-hw4",
    title: "Finish Sections 1.5-1.8",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-02-28",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-hw5",
    title: "Finish Sections 2.1-2.3",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-03-07",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-hw6",
    title: "Finish Sections 2.4-2.6",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-03-14",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-hw7",
    title: "Finish Sections 3.1-3.4",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-03-21",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-exam2",
    title: "EXAM #2",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "exam",
    status: "not-started",
    dueDate: "2026-03-26",
    time: "08:00",
    gradeCategory: "exam",
  },
  {
    id: "math120-hw8",
    title: "Finish Sections 3.5-3.7",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-03-28",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-quiz2",
    title: "Ch 3 & 4 Skills Quizzes Due",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-03-31",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "math120-hw9",
    title: "Finish 3.8-3.9 & 4.1-4.2",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-04-11",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-hw10",
    title: "Finish Sections 4.3-4.7",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-04-18",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-exam3",
    title: "EXAM #3",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "exam",
    status: "not-started",
    dueDate: "2026-04-23",
    time: "08:00",
    gradeCategory: "exam",
  },
  {
    id: "math120-hw11",
    title: "Finish Sections 5.1-5.4",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-04-25",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-quiz3",
    title: "Ch 5 & 6 Skills Quizzes Due",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "quiz",
    status: "not-started",
    dueDate: "2026-05-06",
    time: "23:59",
    gradeCategory: "quiz",
  },
  {
    id: "math120-hw12",
    title: "Finish 5.5-5.7 & 6.1-6.3",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-05-02",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-hw-final",
    title: "Final Homework Cutoff (R.1-6.6)",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "homework",
    status: "not-started",
    dueDate: "2026-05-09",
    time: "N/A",
    gradeCategory: "hw",
  },
  {
    id: "math120-final",
    title: "CUMULATIVE FINAL EXAM",
    class: "Calculus for Business Analysis",
    classCode: "MATH120",
    type: "exam",
    status: "not-started",
    dueDate: "2026-05-12",
    time: "08:00",
    isFinal: true,
    gradeCategory: "final",
  },
];

// Backwards-compatible aliases
export { defaultClasses as classes };
export { defaultGradeWeights as gradeWeights };

// Helper function to calculate late penalty
export function calculateLatePenalty(
  grade: number,
  daysLate: number,
  classCode: string
): number {
  const classInfo = defaultClasses.find((c) => c.code === classCode);
  if (!classInfo?.hasLatePenalty || daysLate <= 0) return grade;
  // 10% deduction per day late
  const penalty = daysLate * 10;
  return Math.max(0, grade - penalty);
}
